<form id="saveCatForm" method="post" action="<?php echo $this->url('categories', ['action' => 'save']) ?>">
    <div class="col-md-12">
        <div class="form-group">
            <input class="form-control" name="category_name" required />
        </div>
        <div class="form-group pull-right">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</form>