<?php if($cat) : ?>
<form id="saveCatForm" method="post" action="<?php echo $this->url('categories', ['action' => 'save']) ?>">
    <div class="col-md-12">
        <div class="form-group">
            <input type="hidden" name="category_id" value="<?php echo $cat->getCategoryId() ?>" />
            <input class="form-control" name="category_name" value="<?php echo $cat->getCategoryName() ?>" required />
        </div>
        <div class="form-group pull-right">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</form>
<?php else : ?>
    <div class="alert alert-danger">
        <strong>Sorry, something went wrong. Please try again!</strong>.
    </div>
<?php endif ?>
