<section id="form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    <h2>Login to your account</h2>

                    <?php
                        // Usable in any of your .phtml files
                        echo $this->flashMessenger()->render();
                        $form = $this->loginForm;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                        <?php echo $this->formElement($form->get('email')); ?>
                        <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('email'));?></span>
                        <?php echo $this->formElement($form->get('password')); ?>
                        <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('password'));?></span>
                        <?php
                            echo $this->formRow($form->get('loginCsrf'));
                            echo $this->formElement($form->get('submit'));
                        ?>
                        <?php
                            echo $this->form()->closeTag($form);
                        ?>
                    </form>
                </div><!--/login form-->
            </div>
            <div class="col-sm-1">
                <h2 class="or">OR</h2>
            </div>
            <div class="col-sm-4">
                <div class="signup-form"><!--sign up form-->
                    <h2>New User Signup!</h2>
                    <form action="#">
                        <input type="text" placeholder="Name"/>
                        <input type="email" placeholder="Email Address"/>
                        <input type="password" placeholder="Password"/>
                        <button type="submit" class="btn btn-default">Signup</button>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </div>
</section><!--/form-->
	