<?php
$params = [];
if(isset($this->id)) {
    $params['id'] = $this->id;
}
if(isset($this->action)) {
    $params['action'] = $this->action;
}
if(isset($this->name)) {
    $query['name'] = $this->name;
}

?>
<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->first; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->previous; ?>">
                        <
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, $params, [
                            'query' => array_merge(['page' => $page], $query )
                        ]);?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->next; ?>">
                        >
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >
                    </a>
                </li>
            <?php endif; ?>

            <?php if ($this->last != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, $params); ?>?page=<?php echo $this->last; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>