<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
								<span class="input-group-btn">
									<button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
								</span>
                </div> <!-- /input-group -->
            </li>
            <li><a href="index.html"><i class="fa fa-dashboard fa-fw"></i>
                    Dashboard</a></li>
            <li><a href="#"><i class="fa fa-tags fa-fw"></i>
                    Categories
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a class="add-category" href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i>&nbsp;Add new</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('categories') ?>"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;View all</a>
                    </li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-shopping-cart fa-fw" aria-hidden="true"></i>
                    Products
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    <li>
                        <a class="add-product" href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i>&nbsp;Add new</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('products') ?>"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;View all</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>