<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Features Items</h2>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Dried Chestnuts.jpg" alt="" />
                    <h2>$56</h2>
                    <p>Dried Chestnuts</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Jumbo Raw Peanuts (In Shell).jpg" alt="" />
                    <h2>$56</h2>
                    <p>Jumbo Raw Peanuts (In Shell)</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Organic Cacao Beans (Raw).jpg" alt="" />
                    <h2>$56</h2>
                    <p>Organic Cacao Beans (Raw)</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Supreme Roasted Mixed Nuts (Unsalted).jpg" alt="" />
                    <h2>$56</h2>
                    <p>Supreme Roasted Mixed Nuts (Unsalted)</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <img src="<?php echo $this->basePath() ?>/images/home/new.png" class="new" alt="" />
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Dry Roasted Edamame (Salted).jpg" alt="" />
                    <h2>$56</h2>
                    <p>Dry Roasted Edamame (Salted)</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <img src="<?php echo $this->basePath() ?>/images/home/sale.png" class="new" alt="" />
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="<?php echo $this->basePath() ?>/images/products/Roasted Almonds (50% Less Salt).jpg" alt="" />
                    <h2>$56</h2>
                    <p>Roasted Almonds (50% Less Salt)</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--features_items-->