<?php echo $this->partial('layout/slider') ?>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    <?php
                        foreach($featuredProduct as $product) :
                            $images = $imageTable->getImagesByProductId($product['product_id']);
                            if(!empty($images)) {
                                $image = IMAGE_URL . $product['category_id'] . '/' . $images[0]['image_name'];
                            } else {
                                $image = '';
                            }
                    ?>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" >
                                <div class="productinfo text-center cursor_hover">
                                    <img class="img-product" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => $product['product_id']]) ?>" alt="" src="<?php echo $image ?>" />
                                    <?php echo '<h2>'.$product['product_price'].CURRENCY.'</h2>'; ?>
                                    <?php echo '<p>'.$product['product_name'].'</p>';?>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                            <?php
                        endforeach;
                    ?>
                </div>

                <?php echo $this->partial('layout/recommended', ['recommenedProduct' => $recommenedProduct, 'imageTable' => $imageTable]) ?>
            </div>
        </div>
    </div>
</section>