<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->basePath('sb_admin/bower_components/bootstrap/dist/css/bootstrap.min.css') ?>" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="<?php echo $this->basePath('sb_admin/bower_components/metisMenu/dist/metisMenu.min.css') ?>" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $this->basePath('sb_admin/dist/css/sb-admin-2.css') ?>" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="<?php echo $this->basePath('sb_admin/bower_components/font-awesome/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        .padding-left-40 {
            padding-left: 40px;
        }
    </style>
</head>

<body>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <?php
                $flash = $this->flashMessenger();
                echo $flash->render('error', array('alert', 'alert-dismissable padding-left-40', 'alert-danger'));
                echo $flash->render('info', array('alert', 'alert-dismissable padding-left-40', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissable padding-left-40', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissable padding-left-40', 'alert-success'));
            ?>
            </div>
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                        <fieldset>
                            <div class="form-group">
                                <!--<input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>-->
                                <?php echo $this->formRow($form->get('email')) ?>
                            </div>
                            <div class="form-group">
                                <!--<input class="form-control" placeholder="Password" name="password" type="password" value="">-->
                                <?php echo $this->formRow($form->get('password')) ?>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <!--<a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>-->
                            <?php echo $this->formSubmit($form->get('submit')) ?>
                        </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<!-- jQuery -->
<script src="<?php echo $this->basePath('sb_admin/bower_components/jquery/dist/jquery.min.js') ?>"></script>

<!-- Bootstrap Core JavaScript -->
<script src="<?php echo $this->basePath('sb_admin/bower_components/bootstrap/dist/js/bootstrap.min.js') ?>"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="<?php echo $this->basePath('sb_admin/bower_components/metisMenu/dist/metisMenu.min.js') ?>"></script>

<!-- Custom Theme JavaScript -->
<script src="<?php echo $this->basePath('sb_admin/dist/js/sb-admin-2.js') ?>"></script>

</body>

</html>
