

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center"><?php echo $category_name; ?></h2>
                    <?php
                        foreach ($products as $product) :
                            $imgs = $imageTable->getImagesByProductId($product['product_id']);
                            $imgUrl = '';
                            if(!empty($imgs)) {
                                $imgUrl = IMAGE_URL . $product['category_id'] . '/' . $imgs[0]['image_name'];
                            }
                    ?>
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => $product['product_id']]) ?>" src="<?php echo $imgUrl ?>" alt="" />
                                        <h2>$<?php echo $product['product_price'] ?></h2>
                                        <p><?php echo $product['product_name'] ?></p>
                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="clearfix"></div>
                    <?php
                    // add at the end of the file after the table
                    echo $this->paginationControl(
                    // the paginator object
                        $this->products,
                        // the scrolling style
                        'sliding',
                        // the partial to use to render the control
                        'layout/paginator',
                        // the route to link to when a user clicks a control link
                        array(
                            'route' => 'category',
                            'id' => $category_id
                        )
                    );
                    ?>
                </div>
                <!--features_items-->
            </div>
        </div>
    </div>
</section>

