

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center"><?php echo $category_name; ?></h2>
                    <?php foreach ($products as $product) : ?>
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => $product->ProductID]) ?>">
                                    <div class="productinfo text-center">
                                        <img src="<?php echo SITE_URL . $product->ProductThumb ?>" alt="" />
                                        <h2>$<?php echo $product->ProductPrice ?></h2>
                                        <p><?php echo $product->ProductName ?></p>
                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="clearfix"></div>
                    <ul class="pagination">
                        <li class="active"><a href="">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href="">&raquo;</a></li>
                    </ul>
                </div>
                <!--features_items-->
            </div>
        </div>
    </div>
</section>

