<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Home | S-Nuts</title>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/ico/favicon.ico'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/prettyPhoto.css'))
            ->prependStylesheet($this->basePath('css/price-range.css'))
            ->prependStylesheet($this->basePath('css/animate.css'))
            ->prependStylesheet($this->basePath('css/main.css'))
            ->prependStylesheet($this->basePath('css/responsive.css'))
        ?>

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-57-precomposed.png">

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/jquery.scrollUp.min.js'))
            ->appendFile($this->basePath('js/price-range.js'))
            ->appendFile($this->basePath('js/jquery.prettyPhoto.js'))
            ->appendFile($this->basePath('js/main.js'))
            ->appendFile($this->basePath('js/myscript.js'))
        ; ?>


    </head>
    <body>

    <?php echo $this->partial('layout/header') ?>

    <?php echo $this->content ?>

    <?php echo $this->partial('layout/footer') ?>

    <?php echo $this->inlineScript() ?>
    </body>
</html>
