<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Home | S-Nuts</title>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/ico/favicon.ico'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/prettyPhoto.css'))
            ->prependStylesheet($this->basePath('css/price-range.css'))
            ->prependStylesheet($this->basePath('css/animate.css'))
            ->prependStylesheet($this->basePath('css/main.css'))
            ->prependStylesheet($this->basePath('css/responsive.css'))
        ?>

        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="<?php echo $this->basePath() ?>/images/ico/apple-touch-icon-57-precomposed.png">

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/jquery.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/jquery.scrollUp.min.js'))
            ->appendFile($this->basePath('js/price-range.js'))
            ->appendFile($this->basePath('js/jquery.prettyPhoto.js'))
            ->appendFile($this->basePath('js/main.js'))
        ; ?>


    </head>
    <body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                                <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="index.html"><img src="<?php echo $this->basePath() ?>/images/home/logo.png" alt="" /></a>
                        </div>
                        <div class="btn-group pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle countryList" data-toggle="dropdown">
                                    Vietnam
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li name="vietnam" class="countryListItem display-none"><a href="#">Vietnam</a></li>
                                    <li name="usa" class="countryListItem"><a href="#">USA</a></li>
                                </ul>
                            </div>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle currencyList" data-toggle="dropdown">
                                    VND
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li name="vietnam" class="currencyListItem display-none"><a href="#">VND</a></li>
                                    <li name="usa" class="currencyListItem"><a href="#">Dollar</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                                <li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                                <li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <?php echo $this->partial('layout/menu') ?>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <input type="text" placeholder="Search"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/header-bottom-->
    </header>
    <!--/header-->

    <?php echo $this->partial('layout/slider') ?>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <?php echo $this->partial('layout/sidebar') ?>
                </div>

                <div class="col-sm-9 padding-right">

                    <?php echo $this->content ?>

                    <?php echo $this->partial('layout/recommend') ?>

                </div>
            </div>
        </div>
    </section>

    <?php echo $this->partial('layout/footer') ?>
    <?php echo $this->inlineScript() ?>
    </body>
</html>
