<?php
$imgs = $imageTable->getImagesByProductId($product['product_id']);
$imgUrl = '';
if(!empty($imgs)) {
    $imgUrl = IMAGE_URL . $product['category_id'] . '/' . $imgs[0]['image_name'];
}
?>
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="product-details">
                    <!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="<?php echo $imgUrl ?>" alt="" />
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="product-information">
                            <!--/product-information-->
                            <h2><?php echo $product['product_name'] ?></h2>
								<span>
									<span>US $<?php echo $product['product_price'] ?></span>
									<label>Quantity:</label>
									<input type="text" value="1" />
									<button type="button" class="btn btn-default cart">
                                        <i class="fa fa-shopping-cart"></i>
                                        Add to cart
                                    </button>
								</span>
                            <p><b>Availability:&nbsp;&nbsp;</b><?php echo $product['is_stock'] == 1 ? 'In Stock' : 'Out of Stock' ?></p>
                            <a href=""><img src="<?php echo IMAGE_DETAIL_URL ?>share.png" class="share img-responsive"  alt="" /></a>
                        </div>
                        <!--/product-information-->
                    </div>
                </div>
                <!--/product-details-->

                <div class="category-tab shop-details-tab">
                    <!--category-tab-->
                    <div class="col-sm-12">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#details" data-toggle="tab">Details</a></li>
                            <li><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
                        </ul>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade active in" id="details" >
                            <p>
                                <?php echo $product['product_desc'] ?>
                            </p>
                        </div>

                        <div class="tab-pane fade" id="reviews" >
                            <div class="col-sm-12">
                                <ul>
                                    <li><a href=""><i class="fa fa-user"></i>EUGEN</a></li>
                                    <li><a href=""><i class="fa fa-clock-o"></i>12:41 PM</a></li>
                                    <li><a href=""><i class="fa fa-calendar-o"></i>31 DEC 2014</a></li>
                                </ul>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                                <p><b>Write Your Review</b></p>

                                <form action="#">
										<span>
											<input type="text" placeholder="Your Name"/>
											<input type="email" placeholder="Email Address"/>
										</span>
                                    <textarea name="" ></textarea>
                                    <b>Rating: </b> <img src="<?php echo IMAGE_DETAIL_URL ?>rating.png" alt="" />
                                    <button type="button" class="btn btn-default pull-right">
                                        Submit
                                    </button>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
                <!--/category-tab-->

                <?php echo $this->partial('layout/recommended', ['recommenedProduct' => $recommenedProduct, 'imageTable' => $imageTable]) ?>
            </div>
        </div>
    </div>
</section>

<?php echo $this->headScript()
    ->appendFile($this->basePath('js/product-details.js')) ?>