<section id="advertisement">
    <div class="container">
        <img src="<?php echo SITE_URL ?>images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center">Features Items</h2>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Dried Chestnuts.jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Dried Chestnuts</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Jumbo Raw Peanuts (In Shell).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Jumbo Raw Peanuts (In Shell)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Organic Cacao Beans (Raw).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Organic Cacao Beans (Raw)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Supreme Roasted Mixed Nuts (Unsalted).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Supreme Roasted Mixed Nuts (Unsalted)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                                <img src="<?php echo SITE_URL ?>images/home/new.png" class="new" alt="" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Dry Roasted Edamame (Salted).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Dry Roasted Edamame (Salted)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                                <img src="<?php echo SITE_URL ?>images/home/sale.png" class="new" alt="" />
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Fresh Chestnuts.jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Fresh Chestnuts</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Roasted Soy Beans (Salted, Whole).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Roasted Soy Beans (Salted, Whole)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products" data-url="<?php echo $this->url('product', ['action' => 'detail', 'id' => 1]) ?>">
                                <div class="productinfo text-center">
                                    <img src="<?php echo SITE_URL ?>images/products/Organic Cacao Beans (Peeled).jpg" alt="" />
                                    <h2>$56</h2>
                                    <p>Organic Cacao Beans (Peeled)</p>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <ul class="pagination">
                        <li class="active"><a href="">1</a></li>
                        <li><a href="">2</a></li>
                        <li><a href="">3</a></li>
                        <li><a href="">&raquo;</a></li>
                    </ul>
                </div>
                <!--features_items-->
            </div>
        </div>
    </div>
</section>

