
<form id="saveProductForm" method="post" action="<?php echo $this->url('products', ['action' => 'save']) ?>">
    <div class="col-md-12">
        <div class="form-group">
            <input type="text" class="form-control" name="product_name" placeholder="Product Name" required />
        </div>
        <div class="form-group">
            <input type="text" class="form-control" name="product_sku" placeholder="Product SKU" required />
        </div>
        <div class="form-group">
            <input type="number" class="form-control" name="product_price" placeholder="Product Price" required />
        </div>
        <div class="form-group">
            <textarea class="form-control" rows="5" name="product_desc"></textarea>
        </div>
        <div class="form-group">
            <select class="form-control" name="category_id">
                <?php foreach ($this->categories as $category): ?>
                    <option value="<?php echo $category->getCategoryId() ?>"><?php echo $category->getCategoryName() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control" name="type">
                <option value="new">New</option>
                <option value="sale">Sale</option>
                <option value="featured">Featured</option>
                <option value="recommended">Recommended</option>
            </select>
        </div>
        <div class="checkbox">
            <label><input type="checkbox" value="1">In Stock</label>
        </div>
         <div class="form-group">
           <label class="control-label">Thumb</label>
            <input id="input-thumb1" name="input1" type="file" class="file fileinput" data-show-upload="false" data-show-caption="true">
        </div>
        <div class="form-group">
           <label class="control-label">Images</label>
            <input id="input-thumb2" name="input2[]" type="file" class="file fileinput" multiple data-show-upload="false" data-show-caption="true">
        </div>
        <div class="form-group pull-right">
            <button type="submit" class="btn btn-success">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</form>
