<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Detail</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><a class="add-product" href="#">Product name</a></div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <div id="dataTables-example_wrapper"
                         class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-md-12 alert-area">
                                <?php echo $this->partial('layout/messages') ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tr>
                                            <td><b>Name:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>SKU:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>Price:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>Description:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>Category:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>Type:</b></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><b>In stock:</b></td>
                                            <td></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
