<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Products</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><a class="add-product" href="#">Add new product</a></div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <div id="dataTables-example_wrapper"
                         class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-md-12 alert-area">

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="dataTables_length" id="dataTables-example_length">
                                    <!--<label>Show <select name="dataTables-example_length"
                                        aria-controls="dataTables-example"
                                        class="form-control input-sm"><option value="10">10</option>
                                            <option value="25">25</option>
                                            <option value="50">50</option>
                                            <option value="100">100</option></select> entries
                                    </label>-->
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div id="dataTables-example_filter" class="dataTables_filter pull-right">
                                    <!--<label>Search:<input type="search"
                                        class="form-control input-sm" placeholder="Enter category name..."
                                        aria-controls="dataTables-example"></label>-->
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table width="100%"
                                       class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline"
                                       id="dataTables-example" role="grid"
                                       aria-describedby="dataTables-example_info" style="width: 100%;">
                                    <thead>
                                    <tr role="row">
                                        <th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending"
                                            style="width: 211px;">Name</th>
                                        <!--<th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending"
                                            style="width: 211px;">SKU</th>-->
                                        <th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending"
                                            style="width: 211px;">Price</th>
                                        <th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending"
                                            style="width: 211px;">Category</th>
                                        <th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Browser: activate to sort column ascending"
                                            style="width: 211px;">Type</th>
                                        <th class="sorting" tabindex="0"
                                            aria-controls="dataTables-example" rowspan="1" colspan="1"
                                            aria-label="Platform(s): activate to sort column ascending"
                                            style="width: 193px;">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($this->products as $product) : ?>
                                        <tr>
                                            <td><?php echo $product->getProductName() ?></td>
                                            <!--<td></td>-->
                                            <td><?php echo $product->getProductPrice() ?></td>
                                            <td><?php echo $this->categoryMapper->getCategoryById($product->getCategoryId())->getCategoryName(); ?></td>
                                            <td>
                                                <?php
                                                if($product->getIsNew() == 1) {
                                                    echo 'New';
                                                } elseif($product->getIsSale() == 1) {
                                                    echo 'Sale';
                                                } elseif($product->getIsFeatured() == 1) {
                                                    echo 'Featured';
                                                } elseif($product->getIsRecommended() == 1) {
                                                    echo 'Recommended';
                                                } else {
                                                    echo 'Normal';
                                                }
                                                ?>
                                            </td>
                                            <td>
                                                <select class="form-control category-action">
                                                    <option value="-1">-----</option>
                                                    <option value="<?php echo $this->url('products', ['action' => 'edit', 'id' => $product->getProductId()]) ?>">Edit</option>
                                                    <option value="<?php echo $this->url('products', ['action' => 'delete', 'id' => $product->getProductId()]) ?>">Delete</option>
                                                    <option value="<?php echo $this->url('products', ['action' => 'detail', 'id' => $product->getProductId()]) ?>">View Detail</option>
                                                </select>
                                            </td>
                                        </tr>
                                    <?php endforeach ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">

                            </div>
                            <div class="col-sm-6">
                                <div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
                                    <?php
                                    // add at the end of the file after the table
                                    echo $this->paginationControl(
                                    // the paginator object
                                        $this->products,
                                        // the scrolling style
                                        'sliding',
                                        // the partial to use to render the control
                                        'admin/paginator',
                                        // the route to link to when a user clicks a control link
                                        array(
                                            'route' => 'products',
                                            'name' => 'haha',
                                            'type' => '1'
                                        )
                                    );
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
