<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">Latest News</h2>
                    <?php foreach ($news as $n) : ?>
                    <div class="single-blog-post">
                        <h3><?php echo $n['news_title'] ?></h3>
                        <div class="post-meta">
                            <ul>
                                <li><i class="fa fa-user"></i> Mac Doe</li>
                                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                            </ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                        </div>
                        <a href="">
                            <img src="<?php echo IMAGE_NEWS_URL . $n['news_image'] ?>" alt="">
                        </a>
                        <p class="read">
                            <?php echo $n['news_short_content'] ?>
                        </p>
                        <a id="readMore" class="btn btn-primary" href="<?php echo $this->url('news', ['id' => $n['news_id']]) ?>">Read More</a>
                    </div>
                    <?php endforeach ?>
                    <div>
                        <?php
                        // add at the end of the file after the table
                        echo $this->paginationControl(
                        // the paginator object
                            $this->news,
                            // the scrolling style
                            'sliding',
                            // the partial to use to render the control
                            'layout/paginator',
                            // the route to link to when a user clicks a control link
                            array(
                                'route' => 'pages',
                                'action' => 'news'
                            )
                        );
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php echo $this->headScript()
    ->appendFile($this->basePath('js/news.js')) ?>