<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php echo $this->partial('layout/category', ['categories' => $categories]) ?>
            </div>
            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">Latest News</h2>
                    <div class="single-blog-post">
                        <h3>Nuts and Heart Health : A Summary Of The Evidence</h3>
                        <div class="post-meta">
                            <ul>
                                <li><i class="fa fa-user"></i> Mac Doe</li>
                                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                            </ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                        </div>
                        <a href="">
                            <img src="<?php echo SITE_URL ?>images/news/banner1.jpg" alt="">
                        </a>
                        <p>Nuts and Heart Health : A Summary Of The Evidence
                            This report is a summary of the latest evidence on nuts and the important role they play in cardiovascular
                            HEALTH. It incorporates a summary of a new systematic literature review of just over 100 studies conducted
                            by academics from Landmark Nutrition and the University of Wollongong’s Smart Food Centre, the findings support
                            a general level health claim that daily nut consumption, as part of a healthy, varied diet, contributes to HEART HEALTH.</p>
                        <a  class="btn btn-primary" href="">Read More</a>
                    </div>
                    <div class="single-blog-post">
                        <h3>The Nut Report: The Big Fat Myth</h3>
                        <div class="post-meta">
                            <ul>
                                <li><i class="fa fa-user"></i> Mac Doe</li>
                                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                            </ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
                        </div>
                        <a href="">
                            <img src="<?php echo SITE_URL ?>images/news/banner2.jpg" alt="">
                        </a>
                        <p>The Nut Report: The Big Fat Myth
                            Nuts and The Big Fat Myth considers evidence spanning the last 24 years on nuts and their impact on weight –
                            including weight management in diets designed to achieve other outcomes, such as lowering cholesterol or
                            stabilising blood glucose.</p>
                        <a  class="btn btn-primary" href="">Read More</a>
                    </div>
                    <div class="single-blog-post">
                        <h3>PREDIMED: A five year Mediterranean and mixed nuts diet study from Spain – summary of the published literature (Updated July 2015)</h3>
                        <div class="post-meta">
                            <ul>
                                <li><i class="fa fa-user"></i> Mac Doe</li>
                                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                            </ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
                        </div>
                        <a href="">
                            <img src="<?php echo SITE_URL ?>images/news/banner3.jpg" alt="">
                        </a>
                        <p>PREDIMED: A five year Mediterranean and mixed nuts diet study from Spain – summary of the published literature (Updated July 2015)
                            This long term study of 7500 people in 16 centres in Spain found eating a Mediterranean diet with a 30g handful of nuts a day
                            improves Heart Disease, Metabolic Syndrome, Diabetes, Weight and Brain function. To date these PREDIMED study groups have
                            published some 155 journal papers in peer reviewed journals and we have summarised those related to nut consumption here.</p>
                        <a  class="btn btn-primary" href="">Read More</a>
                    </div>
                    <div class="pagination-area">
                        <ul class="pagination">
                            <li><a href="" class="active">1</a></li>
                            <li><a href="">2</a></li>
                            <li><a href="">3</a></li>
                            <li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>