<div class="left-sidebar">
    <h2>Category</h2>
    <div class="panel-group category-products" id="accordian">
        <!--category-products-->
        <?php foreach ($categories as $result): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="<?php echo $this->url('category', ['action' => 'index', 'id' => $result['category_id']]) ?>"><?php echo $result['category_name']?></a></h4>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    <!--/category-products-->
</div>