<?php
$flash = $this->flashMessenger();
echo $flash->render('error', array('alert', 'alert-dismissable padding-left-40', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable padding-left-40', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable padding-left-40', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable padding-left-40', 'alert-success'));
?>
